# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: '0 16 * * *'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: initialize git setting.
        run: |
          git config --global user.name "iranika"
          git config --global user.email "7370486+iranika@users.noreply.github.com"
          git remote set-url origin https://iranika:${GITHUB_TOKEN}@github.com/iranika/mo-yoyaku.git
          git pull
          git checkout master
      # Runs a single command using the runners shell
      - name: Run a goyoyaku.ps1
        shell: bash
        run: |
          pwsh goyoyaku.ps1
          (git add goyoyaku.json goyoyaku.js && git commit -m "update goyoyaku.json by github actions" && git push origin master) || echo "No updates"
          
          
